name: Minify WordPress Theme CSS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install clean-css-cli
        run: npm install -g clean-css-cli

      - name: Extract WordPress comment header from style.css
        run: sed -n '/^\/\*/,/\*\//p' style.css > wp-header.txt

      - name: Remove WordPress header from style.css to prepare for minification
        run: sed '1,/^\*\//d' style.css > style-body.css

      - name: Minify CSS body
        run: cleancss -o style.min.css style-body.css

      - name: Assemble final minified style.css with header
        run: |
          cat wp-header.txt > style.css
          echo "" >> style.css
          echo "/* === Fichier CSS minifié automatiquement === */" >> style.css
          cat style.min.css >> style.css

      - name: Clean up
        run: rm -f style-body.css style.min.css wp-header.txt
