name: Build and Release Theme

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.run_number > 1 && !contains(github.event.head_commit.message, 'NORUN')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch Tags
        run: |
          git fetch --tags
          git tag

      - name: Get and Increment Version
        id: get_version
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "1.0.0")
          IFS='.' read -r MAJOR MINOR PATCH <<< "$LAST_TAG"
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          while git rev-parse "refs/tags/$NEW_VERSION" >/dev/null 2>&1; do
            PATCH=$((PATCH + 1))
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          done
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update Version in style.css
        run: |
          sed -i "s/\(Version:\s*\)[0-9.]*/\1$VERSION/" style.css

      - name: Remove and Recreate version.txt to force GitHub cache refresh
        run: |
          rm -f version.txt
          echo $VERSION > version.txt

      - name: Commit version.txt separately to force update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add version.txt
          git commit -m "Force update version.txt to $VERSION"
          git push origin master

      - name: Setup Node.js with npm cache
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Prepare release build folder
        run: |
          mkdir release-build
          rsync -a --exclude=".git" --exclude=".github" --exclude="README.md" --exclude="*.zip" ./ release-build/

      - name: Minify all JS and CSS (except style.css header)
        run: |
          find release-build -type f -name "*.js" -exec ./node_modules/.bin/terser "{}" -o "{}" \;
          find release-build -type f -name "*.css" ! -name "style.css" -exec ./node_modules/.bin/cleancss -o "{}" "{}" \;

      - name: Minify style.css and preserve WordPress header
        run: |
          STYLE_SRC="style.css"
          STYLE_DEST="release-build/style.css"

          HEADER=$(sed -n '/^\/\*\*/,/\*\//p' "$STYLE_SRC")
          START_LINE=$(grep -n '*/' "$STYLE_SRC" | head -n1 | cut -d: -f1)
          BODY_START=$((START_LINE + 1))
          tail -n +"$BODY_START" "$STYLE_SRC" > tmp-body.css

          ./node_modules/.bin/cleancss tmp-body.css -o tmp-body.min.css

          echo "$HEADER" > "$STYLE_DEST"
          echo "" >> "$STYLE_DEST"
          cat tmp-body.min.css >> "$STYLE_DEST"

      - name: Create Theme ZIP
        run: |
          cd release-build
          zip -r ../no-code-tools.zip * .[^.]*

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add style.css version.txt
          git commit -m "Update version to $VERSION" || echo "No changes to commit"
          git push origin master

      - name: Create Git Tag
        run: |
          git tag $VERSION
          git push origin $VERSION

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: "Nouvelle version : ${{ env.VERSION }}"
          draft: false
          prerelease: false
          files: |
            no-code-tools.zip
            version.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
