name: Create Release with Minified Files

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install clean-css-cli
        run: npm install -g clean-css-cli

      - name: Extract WordPress comment header from style.css
        id: extract_header
        run: |
          sed -n '/^\/\*\*/,/\*\//p' style.css > wp-header.txt

      - name: Remove WordPress header from style.css to prepare for minification
        run: |
          sed '1,/^\*\//d' style.css > style-body.css

      - name: Minify CSS
        run: cleancss -o style.min.css style-body.css

      - name: Assemble final minified style.css with header
        run: |
          cat wp-header.txt > release-style.css
          echo "" >> release-style.css
          echo "/* === Fichier CSS minifié automatiquement === */" >> release-style.css
          cat style.min.css >> release-style.css

      - name: Create release ZIP
        run: |
          mkdir release
          cp -r * release/
          cp release-style.css release/style.css
          rm release/style-body.css release/style.min.css release-style.css wp-header.txt || true
          cd release
          zip -r ../release.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
